export default [
    'Barry Harris',
    'Benny Golson',
    'Benny Goodman',
    'Bill Evans',
    'Billie Holiday',
    'Billy Strayhorn',
    'Bobby Hutcherson',
    'Bobby Timmons',
    'Bud Powell',
    'Cannonball Adderley',
    'Cedar Walton',
    'Charlie Parker',
    'Chick Corea',
    'Count Basie',
    'Dave Brubeck',
    'Denzil Best',
    'Dizzy Gillespie',
    'Duke Ellington',
    'Duke Jordan',
    'Duke Pearson',
    'Eubie Blake',
    'Fats Waller',
    'Frank Foster',
    'Frank Rosolino',
    'Freddie Hubbard',
    'George Shearing',
    'Gigi Gryce',
    'Hank Jones',
    'Hank Mobley',
    'Herbie Hancock',
    'Horace Silver',
    'J.J. Johnson',
    'Jackie McLean',
    'James P. Johnson',
    'Jelly Roll Morton',
    'Jimmy Heath',
    'Jimmy Rowles',
    'Joe Henderson',
    'John Coltrane',
    'John Louis',
    'Kenny Clarke',
    'Kenny Dorham',
    'Lee Morgan',
    'Mal Waldron',
    'Mary Lou Williams',
    'Miles Davis',
    'Milt Jackson',
    'Neal Hefti',
    'Oliver Nelson',
    'Oscar Pettiford',
    'Rudy Stevenson',
    'Sonny Clark',
    'Sonny Rollins',
    'Tadd Dameron',
    'Thad Jones',
    'Thelonious Monk',
    'Tommy Flanagan',
    'Victor Feldman',
    'Walter Davis Jr.',
    'Wayne Shorter',
    'Wes Montgomery',
    'Wynton Marsalis'
]
