export default [
    'Alec Wilder',
    'Allie Wrubel',
    'Arthur Johnston',
    'Arthur Schwartz',
    'Ben Oakland',
    'Bernice Petkere',
    'Bronislaw Kaper',
    'Burton Lane',
    'Carl Sigman',
    'Cole Porter',
    'Frank Loesser',
    'Frederick Loewe',
    'Gene De Paul',
    'George Gershwin',
    'Harold Arlen',
    'Harry Barris',
    'Harry Warren',
    'Henry Mancini',
    'Hoagy Carmichael',
    'Irene Kitchings',
    'Irving Berlin',
    'Irving Caesar',
    'J. Fred Coots',
    'Jerome Kern',
    'Jimmy McHugh',
    'Jimmy Van Heusen',
    'Johnny Green',
    'Johnny Mandel',
    'Johnny Mercer',
    'Josef Myrow',
    'Jule Styne',
    'Kurt Weill',
    'Leonard Bernstein',
    'Matt Dennis',
    'Matt Malneck',
    'Ralph Rainger',
    'Ray Noble',
    'Richard A. Whiting',
    'Richard Rodgers',
    'Rube Bloom',
    'Sammy Fain',
    'Sigmund Romberg',
    'Vernon Duke',
    'Victor Young',
    'Vincent Youmans'
]
